services:

  fluentd:
    image: fluent/fluentd:v1.12.0-debian-1.0
    ports:
      - 24224:24224
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ./logs:/fluentd/logs

  app:
    build: .
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    command: uvicorn src.fastapp.main_app:app --host=0.0.0.0 --port=8080
    depends_on:
      - redis
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: app

  worker:
    platform: linux/amd64
    build: .
    command: celery -A src.celery.main_queue.celery_master worker --loglevel=info --autoscale=20,1
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - app
      - redis
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: worker

  redis:
    image: redis:7

  dashboard:
    platform: linux/amd64
    build: .
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - app
      - redis
      - worker
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: dashboard

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 9091:5432
    volumes:
      - ./postgres/temp:/var/lib/postgresql/data
      - ./postgres/sql/stage1Schema.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: postgres

  nginx:
    build: ./nginx
    ports:
      - 9090:80
    depends_on:
      - app
      - dashboard
      - postgres
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: nginx

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: ngrok
