services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 7777:5432
    volumes:
      - ./postgres/postgres_data:/var/lib/postgresql/data
      - ./postgres/sql/stage1Schema.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@domain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - 5050:80
    user: "${UID}:${GID}"
    logging:
      driver: none

  redis:
    image: redis
    ports:
      - 6379:6379

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - 5540:5540
