CREATE TABLE IF NOT EXISTS
	USERS (
		USER_ID NUMERIC PRIMARY KEY,
		FIRST_NAME TEXT,
		LAST_NAME TEXT,
		USERNAME TEXT,
		IS_BOT BOOLEAN DEFAULT FALSE
	);

CREATE TABLE IF NOT EXISTS
	CHATS (
		CHAT_ID NUMERIC PRIMARY KEY,
		TITLE TEXT,
		TYPE TEXT,
		IS_AUTHORIZED BOOLEAN DEFAULT FALSE
	);

CREATE TABLE IF NOT EXISTS
	MESSAGES (
		PG_MESSAGE_ID SERIAL PRIMARY KEY,
		MESSAGE_ID NUMERIC,
		ROLE TEXT NOT NULL,
		USER_ID NUMERIC NOT NULL REFERENCES USERS (USER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
		CHAT_ID NUMERIC NOT NULL REFERENCES CHATS (CHAT_ID) ON DELETE CASCADE ON UPDATE CASCADE,
		MESSAGE TEXT NOT NULL,
		COST NUMERIC DEFAULT NULL::INT,
		INPUT_TOKENS NUMERIC DEFAULT NULL::INT,
		OUTPUT_TOKENS NUMERIC DEFAULT NULL::INT,
		INSERTED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	);